import {useEffect,useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {FaArrowRight,FaCheckCircle,FaLeaf,FaShoppingCart,FaStar} from "react-icons/fa";
import PageLayout from "../layout/PageLayout";
import {getProducts} from "../../services/productService";
import {useShop} from "../../context/ShopContext";
import "./Mangoes.css";
function Mangoes(){const {addToCart,wishlist,toggleWishlist}=useShop();const [catalog,setCatalog]=useState([]);useEffect(()=>{getProducts().then(setCatalog).catch(()=>setCatalog([]));},[]);const varieties=useMemo(()=>Object.values(catalog.reduce((all,p)=>all[p.variety]||all[p.name]?all:{...all,[p.variety||p.name]:p},{})),[catalog]);const hero=varieties[0];return <PageLayout><main className="varieties-page"><section className="varieties-hero"><div><p className="varieties-eyebrow">PICKED AT PERFECT RIPENESS</p><h1>Meet our<br/><em>mango varieties.</em></h1><p>Your collection is managed from the admin dashboard.</p><div className="variety-hero-points"><span><FaLeaf/> Naturally ripened</span><span><FaCheckCircle/> Farm fresh</span></div><Link to="/shop" className="variety-shop-link">Shop all mangoes <FaArrowRight/></Link></div>{hero?.image&&<img src={hero.image} alt={hero.name}/>}</section><section className="varieties-intro"><p>OUR COLLECTION</p><h2>Find your perfect mango</h2><span>New varieties added by the store admin appear here automatically.</span></section><section className="varieties-grid">{varieties.map(product=>{const saved=wishlist.some(item=>item.id===product.id);return <article className="variety-card" key={product.id}><div className="variety-image">{product.image&&<img src={product.image} alt={product.name}/>}<button onClick={()=>toggleWishlist(product)} aria-label={`Save ${product.name}`} className={saved?"saved":""}>♡</button><span>Fresh harvest</span></div><div className="variety-content"><div><h3>{product.name}</h3><p>{product.description}</p></div><div className="variety-rating"><span>{[1,2,3,4,5].map(i=><FaStar key={i}/>)}</span> {product.rating||0} ({product.reviews||0})</div><div className="variety-footer"><strong>₹{product.price} <small>/ {product.weight}</small></strong><button disabled={!product.stockQuantity} onClick={()=>addToCart(product)}><FaShoppingCart/> Add</button></div><Link to={`/products/${product.id}`} className="variety-details">Explore this variety <FaArrowRight/></Link></div></article>})}</section>{!varieties.length&&<p className="empty-products">No mango varieties have been added yet.</p>}</main></PageLayout>}
export default Mangoes;
