import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import PageLayout from "../components/layout/PageLayout";
import { useShop } from "../context/ShopContext";
import { createOrder, getContent, getOrder, getOrders, getProducts } from "../services/productService";
import "./CommercePages.css";
const Title=({children})=><header className="page-title"><p>MAVIINA MANE</p><h1>{children}</h1></header>;
export function DynamicCheckout(){const {cart}=useShop();const [message,setMessage]=useState("");const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);async function submit(e){e.preventDefault();try{const data=new FormData(e.currentTarget);const order=await createOrder({customerName:data.get("name"),phone:data.get("phone"),address:data.get("address"),items:cart.map(item=>({productId:item.id,name:item.name,quantity:item.quantity,price:item.price}))});setMessage(`Order ${order.orderNumber} placed successfully.`);}catch{setMessage("Unable to place the order. Add items to your cart and try again.");}}return <PageLayout><main className="screen"><Title>Checkout</Title><div className="two-column"><form className="panel form-grid" onSubmit={submit}><h2>Delivery address</h2><label>Name<input name="name" required/></label><label>Phone<input name="phone" required/></label><label className="full">Address<textarea name="address" required/></label><button className="green-button full">Place order</button>{message&&<p className="form-success full">{message}</p>}</form><aside className="checkout-summary"><h2>Order summary</h2>{cart.map(item=><div className="summary-item" key={item.id}><img src={item.image} alt=""/><span>{item.name}<br/><small>{item.quantity} Kg</small></span><b>₹{item.price*item.quantity}</b></div>)}<div className="summary-total"><strong>Total <em>₹{total}</em></strong></div></aside></div></main></PageLayout>}
export function DynamicProfile(){const [orders,setOrders]=useState([]);useEffect(()=>{getOrders().then(setOrders).catch(()=>setOrders([]));},[]);const delivered=orders.filter(order=>order.status==="DELIVERED").length;const pending=orders.filter(order=>order.status!=="DELIVERED").length;return <PageLayout><main className="screen"><Title>My account</Title><div className="account-layout"><aside className="account-nav"><b>My Account</b><Link to="/profile">Dashboard</Link><Link to="/orders">My Orders</Link><Link to="/wishlist">Wishlist</Link><Link to="/track-order">Track order</Link></aside><section><div className="metric-grid"><article><span>Total orders</span><b>{orders.length}</b></article><article><span>Delivered</span><b>{delivered}</b></article><article><span>In progress</span><b>{pending}</b></article><article><span>Loyalty points</span><b>{orders.length*50}</b></article></div><section className="panel order-table"><h2>Recent orders <Link to="/orders">View all</Link></h2>{orders.slice(0,5).map(order=><div key={order.id}><b>#{order.orderNumber}</b><span>{new Date(order.createdAt).toLocaleDateString()}</span><span>₹{order.total}</span><small className="status">{order.status}</small></div>)}</section></section></div></main></PageLayout>}
export function DynamicTrackOrder(){const [orderNumber,setOrderNumber]=useState("");const [order,setOrder]=useState(null);const [message,setMessage]=useState("");async function submit(e){e.preventDefault();try{setOrder(await getOrder(orderNumber));setMessage("");}catch{setOrder(null);setMessage("Order not found. Check the order number and try again.");}}return <PageLayout><main className="screen narrow"><Title>Track your order</Title><section className="panel track-panel"><form onSubmit={submit}><label>Order number<input value={orderNumber} onChange={e=>setOrderNumber(e.target.value)} placeholder="ORD1234" required/></label><button className="green-button">Track order</button></form>{message&&<p>{message}</p>}{order&&<ol className="timeline"><li className="complete"><b>Order placed</b><span>{new Date(order.createdAt).toLocaleString()}</span></li><li className={order.status!=="PENDING"?"complete":""}><b>Packed with care</b></li><li className={order.status==="SHIPPED"||order.status==="DELIVERED"?"complete":""}><b>Shipped from our farm</b></li><li className={order.status==="DELIVERED"?"complete":""}><b>{order.status}</b></li></ol>}</section></main></PageLayout>}
export function DynamicAbout(){const [farm,setFarm]=useState(null);const [products,setProducts]=useState([]);useEffect(()=>{getContent("farm").then(item=>setFarm(item.value)).catch(()=>setFarm({}));getProducts().then(setProducts).catch(()=>setProducts([]));},[]);const data=farm||{};return <PageLayout><main className="screen"><section className="farm-hero"><div><p>{data.eyebrow||"FROM OUR FARM"}</p><h1>{data.title||"Farm details coming soon"}</h1><span>{data.description||"The store administrator can add farm information from Admin → Settings."}</span></div>{products[0]?.image&&<img src={products[0].image} alt="Farm harvest"/>}</section><div className="farm-stats">{[[data.happyCustomers,"Happy Customers"],[data.acres,"Acres of Farms"],[data.ordersDelivered,"Orders Delivered"],[data.yearsOfCare,"Years Of Care"]].map(([number,label])=><div key={label}><b>{number||0}+</b><span>{label}</span></div>)}</div><h2 className="section-heading">Our Farm Gallery</h2><div className="gallery-row">{products.slice(0,5).filter(product=>product.image).map(product=><img key={product.id} src={product.image} alt={product.name}/>)}</div></main></PageLayout>}
