import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FiEye, FiEyeOff, FiShield, FiTruck, FiUserCheck } from "react-icons/fi";
import { loginUser, registerUser } from "../services/productService";
import "./UserAuth.css";
import "./ModernOrchard.css";

const initialForm = { name: "", email: "", phone: "", password: "", confirmPassword: "" };
export default function UserAuth() {
  const [mode, setMode] = useState("login"); const [form, setForm] = useState(initialForm); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [showPassword, setShowPassword] = useState(false); const nav = useNavigate();
  useEffect(() => { try { const existing = JSON.parse(localStorage.getItem("customer") || "null"); if (existing) nav(existing.role === "ADMIN" ? "/admin" : "/profile", { replace: true }); } catch { localStorage.removeItem("customer"); } }, [nav]);
  const update = event => setForm({ ...form, [event.target.name]: event.target.value });
  const switchMode = next => { setMode(next); setMessage(""); setShowPassword(false); };
  const strength = form.password.length < 6 ? "Choose 6+ characters" : form.password.length < 10 ? "Good password" : "Strong password";
  async function submit(event) { event.preventDefault(); if (mode === "register" && form.password !== form.confirmPassword) { setMessage("Passwords do not match."); return; } setBusy(true); setMessage(""); try { const user = mode === "login" ? await loginUser(form.email, form.password) : await registerUser({ name: form.name, email: form.email, phone: form.phone, password: form.password }); localStorage.setItem("customer", JSON.stringify(user)); window.dispatchEvent(new Event("customer-auth-changed")); const redirect = new URLSearchParams(window.location.search).get("redirect"); nav(redirect || (user.role === "ADMIN" ? "/admin" : "/profile")); } catch (error) { setMessage(error.message || "Something went wrong. Please try again."); } finally { setBusy(false); } }
  return <main className="customer-auth premium-auth"><section className="auth-story"><p>FROM ORCHARD TO YOUR DOORSTEP</p><h1>Good mangoes start with good care.</h1><span>Shop seasonal harvests, track every order, and meet the farms behind your box.</span><div className="auth-benefits"><div><FiTruck/><span><b>Farm to home</b><small>Freshly packed after harvest</small></span></div><div><FiShield/><span><b>Simple, secure checkout</b><small>Trusted online and COD payments</small></span></div><div><FiUserCheck/><span><b>One useful account</b><small>Orders, tracking and delivery updates</small></span></div></div><Link to="/sell-with-us">Are you a farm partner? Apply to sell with us →</Link></section><section className="customer-auth-card"><p className="auth-eyebrow">MAVIINA MANE</p><h2>{mode === "login" ? "Welcome back" : "Create your account"}</h2><p className="auth-copy">{mode === "login" ? "Sign in to follow your mangoes from farm to home." : "Create an account for faster checkout and order updates."}</p><div className="auth-tabs"><button type="button" className={mode === "login" ? "active" : ""} onClick={() => switchMode("login")}>Sign in</button><button type="button" className={mode === "register" ? "active" : ""} onClick={() => switchMode("register")}>Create account</button></div><form onSubmit={submit}>{mode === "register" && <><label>Full name<input name="name" autoComplete="name" value={form.name} onChange={update} required /></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" value={form.phone} onChange={update} required /></label></>}<label>Email address<input name="email" type="email" autoComplete="email" value={form.email} onChange={update} required /></label><label>Password<span className="password-field"><input name="password" type={showPassword ? "text" : "password"} autoComplete={mode === "login" ? "current-password" : "new-password"} minLength="6" value={form.password} onChange={update} required/><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <FiEyeOff/> : <FiEye/>}</button></span>{mode === "register" && <small className="password-hint">{strength}</small>}</label>{mode === "register" && <label>Confirm password<input name="confirmPassword" type={showPassword ? "text" : "password"} autoComplete="new-password" minLength="6" value={form.confirmPassword} onChange={update} required />{form.confirmPassword && <small className={form.password === form.confirmPassword ? "match" : "mismatch"}>{form.password === form.confirmPassword ? "Passwords match" : "Passwords do not match"}</small>}</label>}{message && <p className="auth-error">{message}</p>}<button className="auth-submit" disabled={busy}>{busy ? "Please wait..." : mode === "login" ? "Sign in to my account" : "Create my account"}</button></form><p className="auth-footer">Want to browse first? <Link to="/shop">Explore mangoes</Link></p></section></main>;
}
